# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ArtifactVersionsListRequestVersion(str, enum.Enum):
    LATEST = "latest"

    def visit(self, latest: typing.Callable[[], T_Result]) -> T_Result:
        if self is ArtifactVersionsListRequestVersion.LATEST:
            return latest()
