# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .agent_identity_config import AgentIdentityConfig
from .agent_identity_owned_by import AgentIdentityOwnedBy


class AgentIdentityManifest(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Agent Identity Name
    """

    type: typing.Literal["agent-identity"] = pydantic.Field(default="agent-identity")
    """
    +value=agent-identity
    """

    identity: AgentIdentityConfig
    tags: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Key-value pairs to categorize this Agent Identity (e.g., by owner or environment).
    """

    owned_by: typing_extensions.Annotated[
        AgentIdentityOwnedBy, FieldMetadata(alias="ownedBy"), pydantic.Field(alias="ownedBy")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
