# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .aws_claude_platform_integrations import AwsClaudePlatformIntegrations
from .aws_claude_platform_provider_account_auth_data import AwsClaudePlatformProviderAccountAuthData
from .aws_region import AwsRegion
from .collaborator import Collaborator
from .owned_by import OwnedBy


class AwsClaudePlatformProviderAccount(UniversalBaseModel):
    """
    AWS Claude Platform
    """

    type: typing.Optional[typing.Literal["provider-account/aws-claude-platform"]] = pydantic.Field(default=None)
    """
    +value=provider-account/aws-claude-platform
    """

    name: str = pydantic.Field()
    """
    The name of the AWS Claude Platform provider account
    """

    workspace_id: str = pydantic.Field()
    """
    Your Claude Platform on AWS workspace ID, in the format wrkspc_<alphanumeric>.
    """

    region: AwsRegion
    auth_data: typing.Optional[AwsClaudePlatformProviderAccountAuthData] = pydantic.Field(default=None)
    """
    Authentication data for the AWS account. Supports SigV4 (access key or assumed role) and API key authentication.
    """

    integrations: typing.Optional[typing.List[AwsClaudePlatformIntegrations]] = pydantic.Field(default=None)
    """
    List of integrations that are associated with the AWS Claude Platform provider account
    """

    collaborators: typing.Optional[typing.List[Collaborator]] = pydantic.Field(default=None)
    """
    List of users who have access to this provider account
    """

    owned_by: typing_extensions.Annotated[
        typing.Optional[OwnedBy], FieldMetadata(alias="ownedBy"), pydantic.Field(alias="ownedBy")
    ] = None
    discount_percent: typing.Optional[float] = pydantic.Field(default=None)
    """
    Discount % applied to upstream list price for this provider account.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
