# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AzureWorkloadIdentityAuth(UniversalBaseModel):
    """
    Workload Identity Federation
    """

    type: typing.Optional[typing.Literal["workload-identity"]] = pydantic.Field(default=None)
    """
    +value=workload-identity
    """

    tenant_id: str = pydantic.Field()
    """
    The Azure AD tenant ID where the application is registered
    """

    client_id: str = pydantic.Field()
    """
    The Azure AD application (client) ID configured with a federated identity credential for the gateway's Kubernetes service account
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
