# This file was auto-generated by Fern from our API Definition.

import typing

from .azure_certificate_auth import AzureCertificateAuth
from .azure_key_auth import AzureKeyAuth

AzureFoundryModelAuthData = typing.Union[AzureKeyAuth, AzureCertificateAuth]
