# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .azure_open_ai_model_deployment_type import AzureOpenAiModelDeploymentType
from .azure_open_ai_model_region import AzureOpenAiModelRegion
from .model_cost_metric import ModelCostMetric
from .model_type import ModelType


class AzureOpenAiModel(UniversalBaseModel):
    """
    Azure OpenAI Model
    """

    type: typing.Literal["integration/model/azure-openai"] = pydantic.Field(default="integration/model/azure-openai")
    """
    +value=integration/model/azure-openai
    """

    name: str = pydantic.Field()
    """
    A descriptive name to identify this model integration in the UI
    """

    model_id: str = pydantic.Field()
    """
    The model deployment name created in your Azure OpenAI resource (e.g., gpt-4-deployment, gpt-35-turbo-deployment). This is NOT the base model name but the deployment name you configured in Azure.
    """

    api_version: str = pydantic.Field()
    """
    The Azure OpenAI API version to use
    """

    foundation_model: typing.Optional[str] = pydantic.Field(default=None)
    """
    The foundation model identifier (e.g., gpt-4o-2024-11-20)
    """

    deployment_type: typing.Optional[AzureOpenAiModelDeploymentType] = pydantic.Field(default=None)
    """
    Global: worldwide processing, Data Zone: US/EU processing only
    """

    region: typing.Optional[AzureOpenAiModelRegion] = pydantic.Field(default=None)
    """
    The Azure region for data-zone deployments
    """

    model_types: typing.List[ModelType] = pydantic.Field()
    """
    Specify the type of the Azure OpenAI model
    """

    cost: typing.Optional[ModelCostMetric] = None
    authorized_subjects: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of subjects that are authorized to access this integration. List of user fqn in format <user_type>:<username>.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
