# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .base_artifact_version_manifest import BaseArtifactVersionManifest
from .subject import Subject


class BaseArtifactVersion(UniversalBaseModel):
    """
    Shared artifact-version fields (identity, manifest union, ML repo).
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the artifact version
    """

    fqn: str = pydantic.Field()
    """
    Fully qualified name of the artifact version in the format '{artifact_type}:{tenant_name}/{ml_repo_name}/{artifact_name}:{version}'
    """

    created_by_subject: Subject = pydantic.Field()
    """
    Subject (user, team, or service account) that created this artifact version
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Timestamp when the artifact version was created
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Timestamp when the artifact version was last updated
    """

    manifest: typing.Optional[BaseArtifactVersionManifest] = None
    ml_repo_id: str = pydantic.Field()
    """
    ID of the ML Repo that this artifact version belongs to
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
