# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class BudgetV2AlertSendTo(enum.StrEnum):
    """
    Whom to notify when an alert fires. `shared` sends to the configured notification targets only. `breaching-user` additionally notifies the user whose usage caused the breach.
    """

    SHARED = "shared"
    BREACHING_USER = "breaching-user"
    _UNKNOWN = "__BUDGETV2ALERTSENDTO_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "BudgetV2AlertSendTo":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        shared: typing.Callable[[], T_Result],
        breaching_user: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is BudgetV2AlertSendTo.SHARED:
            return shared()
        if self is BudgetV2AlertSendTo.BREACHING_USER:
            return breaching_user()
        return _unknown_member(self._value_)
