# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class BudgetUsageEntryMode(enum.StrEnum):
    """
    Budget mode.
    """

    ENFORCE = "enforce"
    AUDIT = "audit"
    ENFORCE_WITH_LOW_PRIORITY = "enforce_with_low_priority"
    _UNKNOWN = "__BUDGETUSAGEENTRYMODE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "BudgetUsageEntryMode":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        enforce: typing.Callable[[], T_Result],
        audit: typing.Callable[[], T_Result],
        enforce_with_low_priority: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is BudgetUsageEntryMode.ENFORCE:
            return enforce()
        if self is BudgetUsageEntryMode.AUDIT:
            return audit()
        if self is BudgetUsageEntryMode.ENFORCE_WITH_LOW_PRIORITY:
            return enforce_with_low_priority()
        return _unknown_member(self._value_)
