# This file was auto-generated by Fern from our API Definition.

import typing

from .budget_v2applies_to_aggregate import BudgetV2AppliesToAggregate
from .budget_v2applies_to_metadata import BudgetV2AppliesToMetadata
from .budget_v2applies_to_per_model import BudgetV2AppliesToPerModel
from .budget_v2applies_to_per_user import BudgetV2AppliesToPerUser
from .budget_v2applies_to_per_virtual_account import BudgetV2AppliesToPerVirtualAccount

BudgetV2AppliesTo = typing.Union[
    BudgetV2AppliesToAggregate,
    BudgetV2AppliesToPerUser,
    BudgetV2AppliesToPerModel,
    BudgetV2AppliesToPerVirtualAccount,
    BudgetV2AppliesToMetadata,
]
