# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CohereKeyAuth(UniversalBaseModel):
    """
    Cohere API Key Auth
    """

    type: typing.Literal["api-key"] = pydantic.Field(default="api-key")
    """
    +value=api-key
    """

    api_key: str = pydantic.Field()
    """
    The API key for Cohere authentication
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
