# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class ComplexityBasedLoadBalanceTargetTier(enum.StrEnum):
    """
    Complexity tier this target serves. Each target serves exactly one tier; a model must not be listed under more than one tier.
    """

    SIMPLE = "simple"
    MEDIUM = "medium"
    COMPLEX = "complex"
    _UNKNOWN = "__COMPLEXITYBASEDLOADBALANCETARGETTIER_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "ComplexityBasedLoadBalanceTargetTier":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        simple: typing.Callable[[], T_Result],
        medium: typing.Callable[[], T_Result],
        complex_: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is ComplexityBasedLoadBalanceTargetTier.SIMPLE:
            return simple()
        if self is ComplexityBasedLoadBalanceTargetTier.MEDIUM:
            return medium()
        if self is ComplexityBasedLoadBalanceTargetTier.COMPLEX:
            return complex_()
        return _unknown_member(self._value_)
