# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CustomHeaderAuth(UniversalBaseModel):
    """
    Static API key or token authentication via request headers. All users share the same credentials.
    """

    type: typing.Literal["header"] = pydantic.Field(default="header")
    """
    +value=header
    """

    headers: typing.Dict[str, str] = pydantic.Field()
    """
    Headers passed to the generic secret server with every request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
