# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CustomRegexPattern(UniversalBaseModel):
    """
    Custom Regex Pattern
    """

    pattern: str = pydantic.Field()
    """
    A custom regex pattern to match against content (e.g., "\\\\b\\\\d{3}-\\\\d{2}-\\\\d{4}\\\\b" for SSN)
    """

    redaction_text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Text to use when redacting matched content (only applicable in mutate mode). Defaults to '[REDACTED]'.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
