# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .gateway_data_type import GatewayDataType


class DataAccessRuleBase(UniversalBaseModel):
    """
    Data Access Rule
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the rule
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description of the rule
    """

    enabled: typing.Optional[bool] = pydantic.Field(default=True)
    """
    Whether this rule is enabled
    """

    subjects: typing.List[str] = pydantic.Field()
    """
    List of subjects that this rule applies to (users, teams, roles)
    """

    data_types: typing.List[GatewayDataType] = pydantic.Field()
    """
    List of data types that this rule applies to
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
