# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .application_summary import ApplicationSummary
from .build_info import BuildInfo
from .deployment_manifest import DeploymentManifest
from .deployment_status import DeploymentStatus
from .recommendation import Recommendation
from .subject import Subject


class Deployment(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier of the deployment
    """

    version: typing.Optional[float] = pydantic.Field(default=None)
    """
    Incremental version number within the application
    """

    fqn: typing.Optional[str] = pydantic.Field(default=None)
    """
    FQN of the deployment
    """

    application_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="applicationId"),
        pydantic.Field(
            alias="applicationId", description="Unique identifier of the application this deployment belongs to"
        ),
    ] = None
    manifest: DeploymentManifest = pydantic.Field()
    """
    Deployment manifest defining the application configuration.
    """

    application: typing.Optional[ApplicationSummary] = pydantic.Field(default=None)
    """
    Summary of the parent application (included when requested)
    """

    created_by_subject: typing_extensions.Annotated[
        Subject,
        FieldMetadata(alias="createdBySubject"),
        pydantic.Field(
            alias="createdBySubject", description="Subject (user or service account) that created this deployment"
        ),
    ]
    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Timestamp when the deployment was created"),
    ] = None
    updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="Timestamp when the deployment was last updated"),
    ] = None
    deployment_builds: typing_extensions.Annotated[
        typing.Optional[typing.List[BuildInfo]],
        FieldMetadata(alias="deploymentBuilds"),
        pydantic.Field(alias="deploymentBuilds", description="Build steps associated with this deployment"),
    ] = None
    deployment_statuses: typing_extensions.Annotated[
        typing.Optional[typing.List[DeploymentStatus]],
        FieldMetadata(alias="deploymentStatuses"),
        pydantic.Field(alias="deploymentStatuses", description="Full history of deployment status transitions"),
    ] = None
    current_status_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="currentStatusId"),
        pydantic.Field(
            alias="currentStatusId", description="Unique identifier of the current deployment status record"
        ),
    ] = None
    current_status: typing_extensions.Annotated[
        typing.Optional[DeploymentStatus],
        FieldMetadata(alias="currentStatus"),
        pydantic.Field(alias="currentStatus", description="Current deployment status object."),
    ] = None
    applied_recommendations: typing_extensions.Annotated[
        typing.Optional[typing.List[Recommendation]],
        FieldMetadata(alias="appliedRecommendations"),
        pydantic.Field(alias="appliedRecommendations", description="Applied recommendations for this deployment"),
    ] = None
    created_by: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdBy"),
        pydantic.Field(alias="createdBy", description="Slug of the subject that created this deployment"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
