# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .flyte_task_custom_truefoundry import FlyteTaskCustomTruefoundry
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class FlyteTaskCustom(UniversalBaseModel):
    truefoundry: FlyteTaskCustomTruefoundry

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
