# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .gateway_data_created_by_filter_operator import GatewayDataCreatedByFilterOperator


class GatewayDataCreatedByFilter(UniversalBaseModel):
    """
    Created By Filter
    """

    field: typing.Literal["created_by"] = pydantic.Field(default="created_by")
    """
    Filter type
    """

    operator: GatewayDataCreatedByFilterOperator = pydantic.Field()
    """
    Comparison operator
    """

    value: typing.List[str] = pydantic.Field()
    """
    List of subjects (users, virtual accounts, teams) to filter by
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
