# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class GetDockerRegistryCredentialsResponse(UniversalBaseModel):
    fqn: str = pydantic.Field()
    """
    Docker registry FQN
    """

    registry_url: typing_extensions.Annotated[
        str, FieldMetadata(alias="registryUrl"), pydantic.Field(alias="registryUrl", description="Docker registry URL")
    ]
    username: str = pydantic.Field()
    """
    Docker registry username
    """

    password: str = pydantic.Field()
    """
    Docker registry password
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
