# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GitRepositoryExistsResponse(UniversalBaseModel):
    exists: bool = pydantic.Field()
    """
    The flag if repository exists or not
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The integration id of the repository
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
