# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .collaborator import Collaborator
from .groq_integrations import GroqIntegrations
from .groq_key_auth import GroqKeyAuth


class GroqProviderAccount(UniversalBaseModel):
    """
    Groq Provider Account
    """

    type: typing.Literal["provider-account/groq"] = pydantic.Field(default="provider-account/groq")
    """
    +value=provider-account/groq
    """

    name: str = pydantic.Field()
    """
    The name of the Groq provider account
    """

    auth_data: GroqKeyAuth
    integrations: typing.Optional[typing.List[GroqIntegrations]] = pydantic.Field(default=None)
    """
    List of integrations that are associated with the Groq provider account
    """

    collaborators: typing.Optional[typing.List[Collaborator]] = pydantic.Field(default=None)
    """
    List of users who have access to this provider account
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
