# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class HeaderMatch(UniversalBaseModel):
    type: typing.Literal["header"] = pydantic.Field(default="header")
    """
    +value=header
    """

    name: str = pydantic.Field()
    """
    +docs=Header name to match on
    +label=Name
    """

    exact_match: str = pydantic.Field()
    """
    +docs=Header value to match on
    +label=Value
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
