# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .image_content_part_image_url_url import ImageContentPartImageUrlUrl


class ImageContentPartImageUrl(UniversalBaseModel):
    """
    +label=Image URL
    +usage=Image URL linking to the image
    """

    url: ImageContentPartImageUrlUrl = pydantic.Field()
    """
    +label=URL
    +usage=Image URL linking to the image
    """

    detail: typing.Optional[str] = pydantic.Field(default=None)
    """
    +label=Details
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
