# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .metric import Metric
from .model_manifest import ModelManifest
from .subject import Subject


class InternalModelVersion(UniversalBaseModel):
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    manifest: ModelManifest
    id: str
    fqn: str
    created_by_subject: Subject
    ml_repo_id: str
    usage_code_snippet: typing.Optional[str] = None
    tags: typing.Optional[typing.List[str]] = None
    model_id: str
    metrics: typing.Optional[typing.List[Metric]] = None
    deployable: bool = False
    artifact_size: typing.Optional[float] = None
    artifact_fqn: str = pydantic.Field()
    """
    Fully qualified name of the parent model
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
