# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class KerasFramework(UniversalBaseModel):
    """
    +label=Keras
    +icon=keras
    """

    type: typing.Literal["keras"] = pydantic.Field(default="keras")
    """
    +label=Type
    +usage=Type of the framework
    +value=keras
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
