# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .application import Application
from .application_debug_info import ApplicationDebugInfo
from .deployment import Deployment
import typing
import pydantic
from .pagination import Pagination
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ListApplicationDeploymentsResponse(UniversalBaseModel):
    data: typing.List[Deployment] = pydantic.Field()
    """
    Array of Deployments
    """

    pagination: Pagination = pydantic.Field()
    """
    Pagination information
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
