# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .job_run_dto import JobRunDto
import pydantic
from .pagination import Pagination
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ListJobRunResponse(UniversalBaseModel):
    data: typing.List[JobRunDto] = pydantic.Field()
    """
    JobRun History
    """

    pagination: Pagination = pydantic.Field()
    """
    Pagination Information
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
