# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .pagination import Pagination
from .team_dto import TeamDto


class ListTeamsResponse(UniversalBaseModel):
    data: typing.List[TeamDto] = pydantic.Field()
    """
    Array of teams matching the query.
    """

    pagination: Pagination = pydantic.Field()
    """
    Pagination metadata.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
