# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class Log(UniversalBaseModel):
    job_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the job.
    """

    log: str = pydantic.Field()
    """
    Log line content.
    """

    stream: str = pydantic.Field()
    """
    Log stream name.
    """

    time: str = pydantic.Field()
    """
    Log timestamp in nanoseconds from the Unix epoch.
    """

    container_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="containerName"),
        pydantic.Field(alias="containerName", description="Name of the container that emitted the log."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
