# This file was auto-generated by Fern from our API Definition.

import typing
from .model_version_manifest import ModelVersionManifest
from .chat_prompt_manifest import ChatPromptManifest
from .artifact_version_manifest import ArtifactVersionManifest

Manifest = typing.Union[ModelVersionManifest, ChatPromptManifest, ArtifactVersionManifest]
