# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .mcp_tool_annotations import McpToolAnnotations


class McpToolMetadata(UniversalBaseModel):
    """
    Description and annotation overrides for a single MCP tool.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Describe what this tool does. This helps AI models understand when to use it.
    """

    annotations: typing.Optional[McpToolAnnotations] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
