# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class McpServerAwsAccessKeyAuth(UniversalBaseModel):
    """
    Authenticate with an AWS access key pair.
    """

    type: typing.Literal["aws-access-key"] = pydantic.Field(default="aws-access-key")
    """
    +value=aws-access-key
    """

    access_key_id: str = pydantic.Field()
    """
    AWS access key ID. Prefer a tfy-secret reference.
    """

    secret_access_key: str = pydantic.Field()
    """
    AWS secret access key. Prefer a tfy-secret reference.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
