# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .metric import Metric


class MetricCollection(UniversalBaseModel):
    key: str = pydantic.Field()
    """
    Name of the metric.
    """

    metrics: typing.List[Metric] = pydantic.Field()
    """
    Time-series history for this metric key.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
