# This file was auto-generated by Fern from our API Definition.

import typing

from .opa_bearer_auth import OpaBearerAuth
from .opa_header_auth import OpaHeaderAuth

OpaAuth = typing.Union[OpaHeaderAuth, OpaBearerAuth]
