# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .data_access_rule_base import DataAccessRuleBase


class OwnDataAccessRule(DataAccessRuleBase):
    """
    Own Data
    """

    scope: typing.Literal["own_data"] = pydantic.Field(default="own_data")
    """
    Data access scope - access to own data only
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
