# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .enforcing_strategy import EnforcingStrategy
from .palo_alto_prisma_airs_guardrail_config_config import PaloAltoPrismaAirsGuardrailConfigConfig
from .palo_alto_prisma_airs_key_auth import PaloAltoPrismaAirsKeyAuth


class PaloAltoPrismaAirsGuardrailConfig(UniversalBaseModel):
    """
    Palo Alto Prisma AIRS
    """

    name: str = pydantic.Field()
    """
    The name of the Guardrail Config.
    """

    description: typing.Optional[str] = pydantic.Field(
        default="Palo Alto Prisma AIRS for AI security and content validation"
    )
    """
    Optional description for this Guardrail Config.
    """

    type: typing.Literal["integration/guardrail-config/palo-alto-prisma-airs"] = pydantic.Field(
        default="integration/guardrail-config/palo-alto-prisma-airs"
    )
    """
    +uiType=Hidden
    +value=integration/guardrail-config/palo-alto-prisma-airs
    """

    operation: typing.Literal["validate"] = pydantic.Field(default="validate")
    """
    The operation type for this guardrail. Palo Alto Prisma AIRS guardrails can only be used for validation.
    """

    enforcing_strategy: EnforcingStrategy
    auth_data: PaloAltoPrismaAirsKeyAuth
    config: PaloAltoPrismaAirsGuardrailConfigConfig

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
