# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class ProviderAccountProvider(enum.StrEnum):
    AWS = "aws"
    GCP = "gcp"
    AZURE = "azure"
    DOCKERHUB = "dockerhub"
    OPENAI = "openai"
    DATABRICKS = "databricks"
    TRUEFOUNDRY = "truefoundry"
    JFROG = "jfrog"
    TTL = "ttl"
    CUSTOM = "custom"
    QUAY = "quay"
    GITHUB = "github"
    GITLAB = "gitlab"
    BITBUCKET = "bitbucket"
    BITBUCKET_DATA_CENTER = "bitbucket_data_center"
    AI21 = "ai21"
    COHERE = "cohere"
    ANTHROPIC = "anthropic"
    ANYSCALE = "anyscale"
    DEEPINFRA = "deepinfra"
    GROQ = "groq"
    MISTRAL_AI = "mistral-ai"
    NOMIC = "nomic"
    PALM = "palm"
    PERPLEXITY_AI = "perplexity-ai"
    TOGETHER_AI = "together-ai"
    OLLAMA = "ollama"
    SLACK = "slack"
    AWS_BEDROCK = "aws-bedrock"
    GOOGLE_VERTEX = "google-vertex"
    GOOGLE_GEMINI = "google-gemini"
    AZURE_OPENAI = "azure-openai"
    AZURE_FOUNDRY = "azure-foundry"
    SELF_HOSTED_MODEL = "self-hosted-model"
    MCP_SERVER_GROUP = "mcp-server-group"
    PAGERDUTY = "pagerduty"
    MS_TEAMS = "ms-teams"
    MODEL_PROVIDER_ACCOUNTS = "model-provider-accounts"
    GUARDRAIL_CONFIG_GROUP = "guardrail-config-group"
    OPENROUTER = "openrouter"
    SAMBANOVA = "sambanova"
    AWS_SAGEMAKER = "aws-sagemaker"
    CEREBRAS = "cerebras"
    WAFER = "wafer"
    HASHICORP = "hashicorp"
    SNOWFLAKE_CORTEX = "snowflake-cortex"
    CLOUDERA = "cloudera"
    XAI = "xai"
    BASETEN = "baseten"
    VIRTUAL_MODEL = "virtual-model"
    ELEVENLABS = "elevenlabs"
    DEEPGRAM = "deepgram"
    CARTESIA = "cartesia"
    CUSTOM_ENDPOINT = "custom-endpoint"
    SMALLEST_AI = "smallest-ai"
    AWS_CLAUDE_PLATFORM = "aws-claude-platform"
    AWS_BEDROCK_MANTLE = "aws-bedrock-mantle"
    _UNKNOWN = "__PROVIDERACCOUNTPROVIDER_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "ProviderAccountProvider":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        aws: typing.Callable[[], T_Result],
        gcp: typing.Callable[[], T_Result],
        azure: typing.Callable[[], T_Result],
        dockerhub: typing.Callable[[], T_Result],
        openai: typing.Callable[[], T_Result],
        databricks: typing.Callable[[], T_Result],
        truefoundry: typing.Callable[[], T_Result],
        jfrog: typing.Callable[[], T_Result],
        ttl: typing.Callable[[], T_Result],
        custom: typing.Callable[[], T_Result],
        quay: typing.Callable[[], T_Result],
        github: typing.Callable[[], T_Result],
        gitlab: typing.Callable[[], T_Result],
        bitbucket: typing.Callable[[], T_Result],
        bitbucket_data_center: typing.Callable[[], T_Result],
        ai21: typing.Callable[[], T_Result],
        cohere: typing.Callable[[], T_Result],
        anthropic: typing.Callable[[], T_Result],
        anyscale: typing.Callable[[], T_Result],
        deepinfra: typing.Callable[[], T_Result],
        groq: typing.Callable[[], T_Result],
        mistral_ai: typing.Callable[[], T_Result],
        nomic: typing.Callable[[], T_Result],
        palm: typing.Callable[[], T_Result],
        perplexity_ai: typing.Callable[[], T_Result],
        together_ai: typing.Callable[[], T_Result],
        ollama: typing.Callable[[], T_Result],
        slack: typing.Callable[[], T_Result],
        aws_bedrock: typing.Callable[[], T_Result],
        google_vertex: typing.Callable[[], T_Result],
        google_gemini: typing.Callable[[], T_Result],
        azure_openai: typing.Callable[[], T_Result],
        azure_foundry: typing.Callable[[], T_Result],
        self_hosted_model: typing.Callable[[], T_Result],
        mcp_server_group: typing.Callable[[], T_Result],
        pagerduty: typing.Callable[[], T_Result],
        ms_teams: typing.Callable[[], T_Result],
        model_provider_accounts: typing.Callable[[], T_Result],
        guardrail_config_group: typing.Callable[[], T_Result],
        openrouter: typing.Callable[[], T_Result],
        sambanova: typing.Callable[[], T_Result],
        aws_sagemaker: typing.Callable[[], T_Result],
        cerebras: typing.Callable[[], T_Result],
        wafer: typing.Callable[[], T_Result],
        hashicorp: typing.Callable[[], T_Result],
        snowflake_cortex: typing.Callable[[], T_Result],
        cloudera: typing.Callable[[], T_Result],
        xai: typing.Callable[[], T_Result],
        baseten: typing.Callable[[], T_Result],
        virtual_model: typing.Callable[[], T_Result],
        elevenlabs: typing.Callable[[], T_Result],
        deepgram: typing.Callable[[], T_Result],
        cartesia: typing.Callable[[], T_Result],
        custom_endpoint: typing.Callable[[], T_Result],
        smallest_ai: typing.Callable[[], T_Result],
        aws_claude_platform: typing.Callable[[], T_Result],
        aws_bedrock_mantle: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is ProviderAccountProvider.AWS:
            return aws()
        if self is ProviderAccountProvider.GCP:
            return gcp()
        if self is ProviderAccountProvider.AZURE:
            return azure()
        if self is ProviderAccountProvider.DOCKERHUB:
            return dockerhub()
        if self is ProviderAccountProvider.OPENAI:
            return openai()
        if self is ProviderAccountProvider.DATABRICKS:
            return databricks()
        if self is ProviderAccountProvider.TRUEFOUNDRY:
            return truefoundry()
        if self is ProviderAccountProvider.JFROG:
            return jfrog()
        if self is ProviderAccountProvider.TTL:
            return ttl()
        if self is ProviderAccountProvider.CUSTOM:
            return custom()
        if self is ProviderAccountProvider.QUAY:
            return quay()
        if self is ProviderAccountProvider.GITHUB:
            return github()
        if self is ProviderAccountProvider.GITLAB:
            return gitlab()
        if self is ProviderAccountProvider.BITBUCKET:
            return bitbucket()
        if self is ProviderAccountProvider.BITBUCKET_DATA_CENTER:
            return bitbucket_data_center()
        if self is ProviderAccountProvider.AI21:
            return ai21()
        if self is ProviderAccountProvider.COHERE:
            return cohere()
        if self is ProviderAccountProvider.ANTHROPIC:
            return anthropic()
        if self is ProviderAccountProvider.ANYSCALE:
            return anyscale()
        if self is ProviderAccountProvider.DEEPINFRA:
            return deepinfra()
        if self is ProviderAccountProvider.GROQ:
            return groq()
        if self is ProviderAccountProvider.MISTRAL_AI:
            return mistral_ai()
        if self is ProviderAccountProvider.NOMIC:
            return nomic()
        if self is ProviderAccountProvider.PALM:
            return palm()
        if self is ProviderAccountProvider.PERPLEXITY_AI:
            return perplexity_ai()
        if self is ProviderAccountProvider.TOGETHER_AI:
            return together_ai()
        if self is ProviderAccountProvider.OLLAMA:
            return ollama()
        if self is ProviderAccountProvider.SLACK:
            return slack()
        if self is ProviderAccountProvider.AWS_BEDROCK:
            return aws_bedrock()
        if self is ProviderAccountProvider.GOOGLE_VERTEX:
            return google_vertex()
        if self is ProviderAccountProvider.GOOGLE_GEMINI:
            return google_gemini()
        if self is ProviderAccountProvider.AZURE_OPENAI:
            return azure_openai()
        if self is ProviderAccountProvider.AZURE_FOUNDRY:
            return azure_foundry()
        if self is ProviderAccountProvider.SELF_HOSTED_MODEL:
            return self_hosted_model()
        if self is ProviderAccountProvider.MCP_SERVER_GROUP:
            return mcp_server_group()
        if self is ProviderAccountProvider.PAGERDUTY:
            return pagerduty()
        if self is ProviderAccountProvider.MS_TEAMS:
            return ms_teams()
        if self is ProviderAccountProvider.MODEL_PROVIDER_ACCOUNTS:
            return model_provider_accounts()
        if self is ProviderAccountProvider.GUARDRAIL_CONFIG_GROUP:
            return guardrail_config_group()
        if self is ProviderAccountProvider.OPENROUTER:
            return openrouter()
        if self is ProviderAccountProvider.SAMBANOVA:
            return sambanova()
        if self is ProviderAccountProvider.AWS_SAGEMAKER:
            return aws_sagemaker()
        if self is ProviderAccountProvider.CEREBRAS:
            return cerebras()
        if self is ProviderAccountProvider.WAFER:
            return wafer()
        if self is ProviderAccountProvider.HASHICORP:
            return hashicorp()
        if self is ProviderAccountProvider.SNOWFLAKE_CORTEX:
            return snowflake_cortex()
        if self is ProviderAccountProvider.CLOUDERA:
            return cloudera()
        if self is ProviderAccountProvider.XAI:
            return xai()
        if self is ProviderAccountProvider.BASETEN:
            return baseten()
        if self is ProviderAccountProvider.VIRTUAL_MODEL:
            return virtual_model()
        if self is ProviderAccountProvider.ELEVENLABS:
            return elevenlabs()
        if self is ProviderAccountProvider.DEEPGRAM:
            return deepgram()
        if self is ProviderAccountProvider.CARTESIA:
            return cartesia()
        if self is ProviderAccountProvider.CUSTOM_ENDPOINT:
            return custom_endpoint()
        if self is ProviderAccountProvider.SMALLEST_AI:
            return smallest_ai()
        if self is ProviderAccountProvider.AWS_CLAUDE_PLATFORM:
            return aws_claude_platform()
        if self is ProviderAccountProvider.AWS_BEDROCK_MANTLE:
            return aws_bedrock_mantle()
        return _unknown_member(self._value_)
