# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .role_binding_permission import RoleBindingPermission
from .role_binding_subject import RoleBindingSubject


class RoleBindingManifest(UniversalBaseModel):
    type: typing.Literal["role-binding"] = pydantic.Field(default="role-binding")
    """
    +value=role-binding
    """

    name: str = pydantic.Field()
    """
    Unique name for this role binding.
    """

    subjects: typing.List[RoleBindingSubject] = pydantic.Field()
    """
    One row per principal; set type and name (email, team name, virtual account name, or external identity name).
    """

    permissions: typing.List[RoleBindingPermission] = pydantic.Field()
    """
    Resource-scoped role grants (resource type, FQN, and role name).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
