# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class StickySessionIdentifierSource(enum.StrEnum):
    """
    Source from which session identifier value will be extracted
    """

    HEADERS = "headers"
    METADATA = "metadata"
    _UNKNOWN = "__STICKYSESSIONIDENTIFIERSOURCE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "StickySessionIdentifierSource":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        headers: typing.Callable[[], T_Result],
        metadata: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is StickySessionIdentifierSource.HEADERS:
            return headers()
        if self is StickySessionIdentifierSource.METADATA:
            return metadata()
        return _unknown_member(self._value_)
