# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TrueFoundryAgentUserMessage(UniversalBaseModel):
    role: typing.Literal["user"] = pydantic.Field(default="user")
    """
    Role of the message sender.
    """

    content: str = pydantic.Field()
    """
    Content of the user message. Supports template variables like {{variable_name}}.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
