# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .ttl_integrations import TtlIntegrations


class TtlProviderAccount(UniversalBaseModel):
    """
    TTL
    """

    type: typing.Literal["provider-account/ttl"] = pydantic.Field(default="provider-account/ttl")
    """
    +value=provider-account/ttl
    """

    name: str = pydantic.Field()
    """
    The name of the provider account.
    """

    integrations: typing.List[TtlIntegrations] = pydantic.Field()
    """
    List of integrations that are associated with the provider account.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
