# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class UserResource(UniversalBaseModel):
    resource_type: typing_extensions.Annotated[
        str, FieldMetadata(alias="resourceType"), pydantic.Field(alias="resourceType", description="Resource Type")
    ]
    resource_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="resourceId"), pydantic.Field(alias="resourceId", description="Resource ID")
    ]
    role_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="roleId"), pydantic.Field(alias="roleId", description="Role ID")
    ]
    resource_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="resourceName"),
        pydantic.Field(alias="resourceName", description="Resource Name (if available)"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
