# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .vertex_key_file_auth_key_file_content import VertexKeyFileAuthKeyFileContent


class VertexKeyFileAuth(UniversalBaseModel):
    """
    Google Cloud Key File Auth
    """

    type: typing.Literal["key-file"] = pydantic.Field(default="key-file")
    """
    +value=key-file
    """

    key_file_content: VertexKeyFileAuthKeyFileContent = pydantic.Field()
    """
    The JSON content of your Google Cloud service account key file
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
