# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class WorkspaceMetadata(UniversalBaseModel):
    istio_injection: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="istioInjection")] = None
    grafana_endpoint: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="grafanaEndpoint")] = None
    is_truefoundry_managed: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="isTruefoundryManaged")
    ] = None
    supported_instance_families: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="supportedInstanceFamilies"),
    ] = None
    supported_nodepools: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="supportedNodepools")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
