# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class GuardrailMetricsChartsDataRequestDtoChartName(str, enum.Enum):
    """
    Chart name
    """

    RATE_OF_REQUESTS_PER_GUARDRAIL = "rateOfRequestsPerGuardrail"
    LATENCY_PER_GUARDRAIL = "latencyPerGuardrail"
    FLAGGED_RATE_OF_REQUESTS_PER_GUARDRAIL = "flaggedRateOfRequestsPerGuardrail"
    MUTATED_RATE_OF_REQUESTS_PER_GUARDRAIL = "mutatedRateOfRequestsPerGuardrail"
    INPUT_REQUESTS_BREAKDOWN_PER_GUARDRAIL = "inputRequestsBreakdownPerGuardrail"
    OUTPUT_REQUESTS_BREAKDOWN_PER_GUARDRAIL = "outputRequestsBreakdownPerGuardrail"
    LATENCY_SUMMARY_PER_GUARDRAIL = "latencySummaryPerGuardrail"
    GUARDRAIL_ERRORS = "guardrailErrors"

    def visit(
        self,
        rate_of_requests_per_guardrail: typing.Callable[[], T_Result],
        latency_per_guardrail: typing.Callable[[], T_Result],
        flagged_rate_of_requests_per_guardrail: typing.Callable[[], T_Result],
        mutated_rate_of_requests_per_guardrail: typing.Callable[[], T_Result],
        input_requests_breakdown_per_guardrail: typing.Callable[[], T_Result],
        output_requests_breakdown_per_guardrail: typing.Callable[[], T_Result],
        latency_summary_per_guardrail: typing.Callable[[], T_Result],
        guardrail_errors: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is GuardrailMetricsChartsDataRequestDtoChartName.RATE_OF_REQUESTS_PER_GUARDRAIL:
            return rate_of_requests_per_guardrail()
        if self is GuardrailMetricsChartsDataRequestDtoChartName.LATENCY_PER_GUARDRAIL:
            return latency_per_guardrail()
        if self is GuardrailMetricsChartsDataRequestDtoChartName.FLAGGED_RATE_OF_REQUESTS_PER_GUARDRAIL:
            return flagged_rate_of_requests_per_guardrail()
        if self is GuardrailMetricsChartsDataRequestDtoChartName.MUTATED_RATE_OF_REQUESTS_PER_GUARDRAIL:
            return mutated_rate_of_requests_per_guardrail()
        if self is GuardrailMetricsChartsDataRequestDtoChartName.INPUT_REQUESTS_BREAKDOWN_PER_GUARDRAIL:
            return input_requests_breakdown_per_guardrail()
        if self is GuardrailMetricsChartsDataRequestDtoChartName.OUTPUT_REQUESTS_BREAKDOWN_PER_GUARDRAIL:
            return output_requests_breakdown_per_guardrail()
        if self is GuardrailMetricsChartsDataRequestDtoChartName.LATENCY_SUMMARY_PER_GUARDRAIL:
            return latency_summary_per_guardrail()
        if self is GuardrailMetricsChartsDataRequestDtoChartName.GUARDRAIL_ERRORS:
            return guardrail_errors()
